import { QueryBuilder } from './query-builder.js';
import type { FindManyOptions } from './query-builder.js';
import type { ModelDefinition } from './schema.js';

// ─────────────────────────────────────────────────────────────────────────────
// DB executor interface — decouples ModelClient from any specific driver.
// The client.ts module injects a concrete implementation at runtime.
// ─────────────────────────────────────────────────────────────────────────────

export interface DbExecutor {
  query<R = Record<string, unknown>>(sql: string, params: unknown[]): Promise<R[]>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Validation helpers
// ─────────────────────────────────────────────────────────────────────────────

function validateData<T extends Record<string, unknown>>(
  model: ModelDefinition<T>,
  data: Partial<T>,
  requireAllNonOptional = false,
): void {
  for (const [key, meta] of Object.entries(model.columns)) {
    const value = (data as Record<string, unknown>)[key];

    if (requireAllNonOptional && !meta.optional && key !== 'id' && value === undefined) {
      throw new Error(`[orm] Field "${key}" is required on model "${model.tableName}"`);
    }

    if (value === undefined || value === null) continue;

    const actualType = typeof value;
    if (meta.kind === 'date') {
      if (!(value instanceof Date) && typeof value !== 'string') {
        throw new Error(
          `[orm] Field "${key}" in "${model.tableName}" must be a Date or ISO string, got ${actualType}`,
        );
      }
    } else if (actualType !== meta.kind) {
      throw new Error(
        `[orm] Field "${key}" in "${model.tableName}" must be ${meta.kind}, got ${actualType}`,
      );
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// ModelClient<T> — the per-model CRUD interface exposed to the application.
// ─────────────────────────────────────────────────────────────────────────────

export class ModelClient<T extends Record<string, unknown>> {
  private readonly qb: QueryBuilder<T>;

  constructor(
    private readonly model: ModelDefinition<T>,
    private readonly executor: DbExecutor,
  ) {
    this.qb = new QueryBuilder<T>(model.tableName);
  }

  /**
   * Insert a new record.
   * The `id` field (if present in the schema) is excluded from the input —
   * it is expected to be generated by the database (SERIAL / BIGSERIAL).
   *
   * @example
   * const todo = await db.todo.create({ title: "Buy milk", completed: false });
   */
  async create(data: Omit<T, 'id'>): Promise<T> {
    validateData(this.model, data as Partial<T>, true);
    const { sql, params } = this.qb.buildInsert(data);
    const rows = await this.executor.query<T>(sql, params);
    const row = rows[0];
    if (!row) throw new Error(`[orm] Insert into "${this.model.tableName}" returned no row`);
    return row;
  }

  /**
   * Find a single record by its primary key (`id`).
   * Returns `null` if not found.
   *
   * @example
   * const todo = await db.todo.findOne(1);
   */
  async findOne(id: number | string): Promise<T | null> {
    const { sql, params } = this.qb.buildFindOne(id);
    const rows = await this.executor.query<T>(sql, params);
    return rows[0] ?? null;
  }

  /**
   * Find multiple records with optional filtering, ordering, and pagination.
   *
   * @example
   * const todos = await db.todo.findMany({ where: { completed: false } });
   * const page  = await db.todo.findMany({ limit: 10, offset: 20 });
   */
  async findMany(options: FindManyOptions<T> = {}): Promise<T[]> {
    const { sql, params } = this.qb.buildFindMany(options);
    return this.executor.query<T>(sql, params);
  }

  /**
   * Update a record by `id`. Only the supplied fields are updated.
   * Returns the updated record.
   *
   * @example
   * const updated = await db.todo.update(1, { completed: true });
   */
  async update(id: number | string, data: Partial<Omit<T, 'id'>>): Promise<T> {
    validateData(this.model, data as Partial<T>);
    const { sql, params } = this.qb.buildUpdate(id, data);
    const rows = await this.executor.query<T>(sql, params);
    const row = rows[0];
    if (!row) throw new Error(`[orm] No record with id=${id} in "${this.model.tableName}"`);
    return row;
  }

  /**
   * Delete a record by `id`.
   *
   * @example
   * await db.todo.delete(1);
   */
  async delete(id: number | string): Promise<void> {
    const { sql, params } = this.qb.buildDelete(id);
    await this.executor.query(sql, params);
  }

  /**
   * Count records with optional filtering.
   *
   * @example
   * const total = await db.todo.count({ where: { completed: true } });
   */
  async count(where?: Partial<T>): Promise<number> {
    const { sql, params } = this.qb.buildCount(where);
    const rows = await this.executor.query<{ count: string }>(sql, params);
    return parseInt(rows[0]?.count ?? '0', 10);
  }
}
